# Generated by Django 5.2.1 on 2025-06-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_littleheart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='little_heart_users',
        ),
    ]
