# Generated by Django 5.2.1 on 2025-06-06 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_littleheart', '0003_otpverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
