# Generated by Django 5.2.1 on 2025-06-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_littleheart', '0007_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('service_type', models.CharField(max_length=50)),
                ('add_ons', models.JSONField(default=list)),
                ('date_time', models.DateTimeField()),
                ('pets', models.JSONField(default=list)),
            ],
        ),
    ]
