# Generated by Django 5.2.1 on 2025-06-10 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_littleheart', '0008_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
