# Generated by Django 5.2.1 on 2025-06-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_littleheart', '0011_remove_booking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='littleheart@gmail.com', max_length=50),
        ),
    ]
