# Generated by Django 5.2.1 on 2025-06-12 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_littleheart', '0012_booking_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
