# Generated by Django 5.2.1 on 2025-06-17 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_littleheart', '0014_calendarevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarEvent',
        ),
    ]
