# Generated by Django 5.2.1 on 2025-06-18 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_littleheart', '0016_calendarevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarEvent',
        ),
    ]
